# Set editor
export EDITOR='atom -w'

export PATH="$HOME/.bin:$PATH"

# recommended by brew doctor
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Added for Node:
export PATH="$PATH:/usr/local/lib/node_modules"
source $(brew --prefix nvm)/nvm.sh

### rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh --no-rehash)"

### Added for ChefDK
export PATH="/opt/chefdk/bin:$PATH"

# Setup rubygems cli
eval "$($HOME/rubygems/meg/bin/meg init -)"

# Setup go env
export GOPATH=~/gocode
export GOBIN=$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
